import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-[#4b2c85] text-white font-sans">
        <main className="w-full max-w-[700px] mx-auto min-h-screen shadow-2xl bg-[#4b2c85] relative overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
